version: "3"
services:
  app:
    container_name: sample-app
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - NODE_ENV=$NODE_ENV
        - DOCKER_BUILDKIT=1
    ports:
      - 3000:3000
    stop_signal: SIGINT
    stdin_open: true
    tty: true
