import { useState } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import { useRecoilState } from 'recoil'
import { authState, youtubeState } from 'state/auth'
import styles from '../styles/Home.module.css'
import { Modal } from 'components/Modal'

const Home: NextPage = () => {
  const [openModal, setOpenModal] = useState(false)
  const [auth] = useRecoilState(authState)
  const [youtube] = useRecoilState(youtubeState)
  console.log(auth)

  const onClose = () => {
    setOpenModal(false)
  }
  const onClick = () => {
    setOpenModal(true)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Google OAuth and YouTube Channel ID Viewer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Modal open={openModal} onClose={onClose} />
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        {auth.email && auth.email !== '' ? (
          <div>
            <p>Email: {auth.email}</p>
            <p>YouTube Channel ID: {youtube.channelId}</p>
            <p>YouTube View Count: {youtube.viewCount}</p>
            <p>YouTube Video Count: {youtube.videoCount}</p>
            <p>YouTube Keywords: {youtube.keywords}</p>
            <p>YouTube Description: {youtube.description}</p>
          </div>
        ) : (
          <div>
            <button onClick={onClick}>Start Registration</button>
          </div>
        )}
      </main>
    </div>
  )
}

export default Home
