import type { NextPage } from 'next'
import Link from 'next/link'
import Head from 'next/head'
import { useRecoilState } from 'recoil'
import { authState } from 'state/auth'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const [auth] = useRecoilState(authState)
  const redirectUri = encodeURI(process.env.NEXT_PUBLIC_AUTH_REDIRECT_URI || '')
  const scope = encodeURI(
    'https://www.googleapis.com/auth/youtube.readonly https://www.googleapis.com/auth/userinfo.email'
  )
  const url = `https://accounts.google.com/o/oauth2/auth?client_id=${process.env.NEXT_PUBLIC_CLIENT_ID}&redirect_uri=${redirectUri}&scope=${scope}&response_type=token`

  return (
    <div className={styles.container}>
      <Head>
        <title>Google OAuth and YouTube Channel ID Viewer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        {auth.email && auth.email !== '' ? (
          <div>
            <p>Email: {auth.email}</p>
            <p>YouTube Channel ID: {auth.channelId}</p>
          </div>
        ) : (
          <div>
            <Link href={url} passHref>
              <button>Google Login</button>
            </Link>
          </div>
        )}
      </main>
    </div>
  )
}

export default Home
